name: Run Tests
on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:

  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      REPORTS_DIR: .reports
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: pip install -e .

      - name: Install Pytest
        run: pip install pytest pytest-cov

      - name: Prepare working directory
        run: mkdir -p $REPORTS_DIR

      - name: Run Pytest
        id: pytest
        run: |
          pytest -v --cov \
            --cov-report=json:$REPORTS_DIR/pytest-report.json \
            --cov-report=term | tee $REPORTS_DIR/pytest-report.txt || true

          python -c "
          import json
          coverage = json.load(open('$REPORTS_DIR/pytest-report.json'))['totals']['percent_covered_display']
          print(f'percent_covered={coverage}', file=open('$GITHUB_OUTPUT', 'a'))"

      - name: Create Coverage Badge
        # https://github.com/marketplace/actions/dynamic-badges
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
           auth: ${{ secrets.GIST_TOKEN }}
           gistID: afe47ca11d7b469e40efab6eaede1cce
           filename: coverage-badge.json
           label: Test Coverage
           message: ${{ steps.pytest.outputs.percent_covered }}%
           valColorRange: ${{ steps.pytest.outputs.percent_covered }}
           minColorRange: 25
           maxColorRange: 60
           namedLogo: pytest

      - name: Publish Job Summary
        run: |
          {
            printf "<details><summary>Coverage report</summary>\n"
            printf '\n```\n'
            awk '/^-+ coverage:/, /^TOTAL/' $REPORTS_DIR/pytest-report.txt
            printf '\n```\n'
            printf '</details>\n\n'

            printf '<details><summary>Pytest report</summary>\n'
            printf '\n```\n'
            awk 'NR == 1 {next}; /^-+ coverage:/ {exit}; {print}' $REPORTS_DIR/pytest-report.txt
            printf '\n```\n'
            printf '</details>\n\n'
          } > $GITHUB_STEP_SUMMARY
